### ISSUE TITLE
Installation on OSX

### ISSUE THREAD

**Issue by jluastro** [valboz/VBBinaryLensing#11]
I am having an installation issue on OS X 10.12 related to C++ STD libraries. I am using MacPorts and have gcc49 installed (although I have tried this with gcc6 as well and have the same issue). 

When I try 

`pip install VBBinaryLensing
`
I get the following:
```
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/VBBinaryLensing
    creating build/temp.macosx-10.7-x86_64-3.6/VBBinaryLensing/lib
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/envs/astroconda/include -arch x86_64 -I/anaconda/envs/astroconda/include -arch x86_64 -I/anaconda/envs/astroconda/include/python3.6m -I/Users/jlu/.local/include/python3.6m -I/anaconda/envs/astroconda/include/python3.6m -c VBBinaryLensing/lib/python_bindings.cpp -o build/temp.macosx-10.7-x86_64-3.6/VBBinaryLensing/lib/python_bindings.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="2.0.5" -std=c++14 -fvisibility=hidden
    gcc: error: unrecognized command line option '-stdlib=libc++'
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda/envs/astroconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/l6/wjkm4dss1b96ghyby7qmvc2c0000gn/T/pip-install-a2mr2nd4/VBBinaryLensing/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/l6/wjkm4dss1b96ghyby7qmvc2c0000gn/T/pip-record-08wlbllk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/l6/wjkm4dss1b96ghyby7qmvc2c0000gn/T/pip-install-a2mr2nd4/VBBinaryLensing/

```
I tried cloning the repo and it builds fine; but then I get the following error when I import VBBinaryLensing, clearly indicating that it didn't build with access to stdlib

```
In [1]: import VBBinaryLensing
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-92f55d854843> in <module>()
----> 1 import VBBinaryLensing

ImportError: dlopen(/anaconda/envs/astroconda/lib/python3.6/site-packages/VBBinaryLensing-2.0.5-py3.6-macosx-10.7-x86_64.egg/VBBinaryLensing.cpython-36m-darwin.so, 2): Symbol not found: __ZSt24__throw_out_of_range_fmtPKcz
  Referenced from: /anaconda/envs/astroconda/lib/python3.6/site-packages/VBBinaryLensing-2.0.5-py3.6-macosx-10.7-x86_64.egg/VBBinaryLensing.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda/envs/astroconda/lib/python3.6/site-packages/VBBinaryLensing-2.0.5-py3.6-macosx-10.7-x86_64.egg/VBBinaryLensing.cpython-36m-darwin.so
```

**Comment by ebachelet** [comment]
Hi Jessica

Thanks for reporting this. I will have a look asap to this.

**Comment by lisadang27** [comment]
Hello, thanks for reporting this, I have the same issue macOS Mojave 10.14

**Comment by lisadang27** [comment]
I successfully installed VBBinaryLensing just by cloning the repository and running the setup.py script!
I think an update to the pip installation should do the trick.

**Comment by jluastro** [comment]
I tried that but got an error on import. That is the second half of my issue. Do you not see the import issue?

**Comment by lisadang27** [comment]
I didn't have any issues importing VBBinaryLensing, sorry I couldn't be more help

**Comment by Nijaid** [comment]
I'm getting the same error as jluastro, has this issue been addressed since then? My pip installation lists
`absl-py                            0.5.0     
acstools                           3.0.0     
alabaster                          0.7.10    
anaconda-client                    1.6.14    
anaconda-project                   0.8.2     
appnope                            0.1.0     
asdf                               2.3.3     
asn1crypto                         0.24.0    
asteval                            0.9.13    
astor                              0.7.1     
astroid                            1.6.3     
astroimtools                       0.2       
astropy                            3.2.1     
astropy-sphinx-theme               1.1       
astroquery                         0.3.9     
atari-py                           0.1.4     
atomicwrites                       1.3.0     
attrs                              18.1.0    
Babel                              2.5.3     
backcall                           0.1.0     
backports.shutil-get-terminal-size 1.0.0     
beautifulsoup4                     4.6.0     
bitarray                           0.8.1     
bkcharts                           0.2       
blaze                              0.11.3    
bleach                             2.1.3     
bokeh                              0.12.16   
boto                               2.48.0    
Bottleneck                         1.2.1     
Box2D                              2.3.2     
calcos                             3.3.5     
certifi                            2019.6.16 
cffi                               1.11.5    
chardet                            3.0.4     
click                              6.7       
cloudpickle                        0.5.3     
clyent                             1.2.2     
colorama                           0.3.9     
colorlog                           3.1.4     
contextlib2                        0.5.5     
costools                           1.2.3     
coverage                           4.5.3     
coveralls                          1.8.1     
crds                               7.3.3     
cryptography                       2.7       
cycler                             0.10.0    
Cython                             0.28.2    
cytoolz                            0.9.0.1   
d2to1                              0.2.12    
dask                               0.17.5    
datashape                          0.5.4     
decorator                          4.3.0     
defusedxml                         0.6.0     
dill                               0.2.9     
distributed                        1.21.8    
docopt                             0.6.2     
docutils                           0.14      
drizzlepac                         2.2.6     
dynesty                            0.9.5.3   
emcee                              3.0rc2    
entrypoints                        0.2.3     
et-xmlfile                         1.0.1     
fastcache                          1.0.2     
filelock                           3.0.4     
fitsblender                        0.3.5     
Flask                              1.0.2     
Flask-Cors                         3.0.4     
future                             0.16.0    
gast                               0.2.0     
gevent                             1.3.0     
ginga                              2.7.2     
glfw                               1.7.0     
glob2                              0.6       
glue-core                          0.12.0    
glue-vispy-viewers                 0.6       
glueviz                            0.9.1     
gmpy2                              2.0.8     
greenlet                           0.4.13    
grpcio                             1.12.1    
gwcs                               0.10.0    
gym                                0.10.5    
h5py                               2.8.0     
heapdict                           1.0.0     
htc-utils                          0.1.0     
html5lib                           1.0.1     
idna                               2.6       
imageio                            2.5.0     
imagesize                          1.0.0     
imexam                             0.8.1     
importlib-metadata                 0.17      
ipykernel                          4.8.2     
ipython                            6.4.0     
ipython-genutils                   0.2.0     
ipywidgets                         7.2.1     
isort                              4.3.4     
itsdangerous                       0.24      
jdcal                              1.4       
jedi                               0.12.0    
Jinja2                             2.10      
joblib                             0.13.2    
jsonschema                         2.6.0     
jupyter                            1.0.0     
jupyter-client                     5.2.3     
jupyter-console                    5.2.0     
jupyter-core                       4.4.0     
jupyterlab                         0.32.1    
jupyterlab-launcher                0.10.5    
jwxml                              0.3.0     
keyring                            18.0.0    
kiwisolver                         1.0.1     
lazy-object-proxy                  1.3.1     
llvmlite                           0.23.1    
locket                             0.2.0     
lxml                               4.2.1     
Markdown                           2.6.11    
MarkupSafe                         1.0       
matplotlib                         3.1.0     
mccabe                             0.6.1     
mistune                            0.8.3     
mkl-fft                            1.0.12    
mkl-random                         1.0.2     
mkl-service                        2.0.2     
mock                               3.0.5     
more-itertools                     4.1.0     
mosviz                             0.1.0     
mpmath                             1.0.0     
msgpack                            0.6.1     
msgpack-python                     0.5.6     
mujoco-py                          1.50.1.56 
multipledispatch                   0.5.0     
nbconvert                          5.3.1     
nbformat                           4.4.0     
networkx                           2.1       
nictools                           1.1.4     
nltk                               3.3       
nose                               1.3.7     
notebook                           5.5.0     
numba                              0.38.0    
numexpr                            2.6.6     
numpy                              1.16.4    
numpydoc                           0.8.0     
odo                                0.5.1     
olefile                            0.45.1    
openpyxl                           2.5.3     
packaging                          17.1      
pandas                             0.24.2    
pandocfilters                      1.4.2     
Parsley                            1.3       
parso                              0.2.0     
partd                              0.3.8     
path.py                            11.0.1    
pathlib2                           2.3.2     
patsy                              0.5.0     
pep8                               1.7.1     
pexpect                            4.5.0     
photutils                          0.6       
pickleshare                        0.7.4     
Pillow                             5.1.0     
pip                                10.0.1    
pkgconfig                          1.4.0     
pkginfo                            1.4.2     
plotly                             3.10.0    
pluggy                             0.6.0     
ply                                3.11      
poppy                              0.8.0     
prometheus-client                  0.6.0     
prompt-toolkit                     1.0.15    
protobuf                           3.6.0     
psutil                             5.4.5     
ptyprocess                         0.5.2     
py                                 1.5.3     
py-expression-eval                 0.3.3     
pybind11                           2.3.0     
pycodestyle                        2.4.0     
pycosat                            0.6.3     
pycparser                          2.18      
pycrypto                           2.6.1     
pycurl                             7.43.0.2  
pyds9                              1.9.dev211
pyFFTW                             0.9.2     
pyflakes                           1.6.0     
pyglet                             1.3.2     
Pygments                           2.2.0     
pyLIMA                             0.1.5     
pylint                             1.8.4     
pymultinest                        2.6       
pyodbc                             4.0.23    
PyOpenGL                           3.1.1a1   
pyOpenSSL                          18.0.0    
pyparsing                          2.2.0     
pyqtgraph                          0.10.0    
pysiaf                             0.1.8     
pySLALIB                           1.0.4     
PySocks                            1.6.8     
pysynphot                          0.9.12    
pytest                             3.5.1     
pytest-arraydiff                   0.3       
pytest-astropy                     0.3.0     
pytest-doctestplus                 0.3.0     
pytest-openfiles                   0.3.0     
pytest-remotedata                  0.2.1     
python-dateutil                    2.7.3     
pytz                               2018.4    
PyWavelets                         1.0.3     
PyYAML                             3.12      
pyzmq                              17.0.0    
QtAwesome                          0.4.4     
qtconsole                          4.3.1     
QtPy                               1.4.1     
radio-beam                         0.2       
reftools                           1.7.4     
requests                           2.18.4    
retrying                           1.3.3     
rope                               0.10.7    
ruamel-yaml                        0.15.35   
scikit-image                       0.15.0    
scikit-learn                       0.21.2    
scipy                              1.2.1     
seaborn                            0.8.1     
semantic-version                   2.6.0     
Send2Trash                         1.5.0     
setuptools                         39.1.0    
simplegeneric                      0.8.1     
singledispatch                     3.4.0.3   
six                                1.11.0    
snowballstemmer                    1.2.1     
sortedcollections                  0.6.1     
sortedcontainers                   1.5.10    
soupsieve                          1.8       
spectral-cube                      0.4.3     
specutils                          0.2.2     
specviz                            0.5.0     
spherical-geometry                 1.2.10    
Sphinx                             1.7.4     
sphinx-astropy                     1.1.1     
sphinx-automodapi                  0.8       
sphinx-gallery                     0.4.0     
sphinxcontrib-applehelp            1.0.1     
sphinxcontrib-devhelp              1.0.1     
sphinxcontrib-htmlhelp             1.0.2     
sphinxcontrib-jsmath               1.0.1     
sphinxcontrib-qthelp               1.0.2     
sphinxcontrib-serializinghtml      1.1.3     
sphinxcontrib-websupport           1.0.1     
spyder                             3.2.8     
SQLAlchemy                         1.2.7     
statsmodels                        0.9.0     
stginga                            1.0       
stistools                          1.3.0     
stregion                           1.1.4     
stsci.convolve                     2.2.2     
stsci.distutils                    0.3.8.dev0
stsci.image                        2.3.1     
stsci.imagemanip                   1.1.4     
stsci.imagestats                   1.6.2     
stsci.ndimage                      0.10.3    
stsci.skypac                       1.0.4     
stsci.stimage                      0.2.2     
stsci.tools                        3.4.13    
stwcs                              1.4.2     
sympy                              1.1.1     
tables                             3.4.3     
tblib                              1.3.2     
tensorboard                        1.10.0    
tensorflow                         1.10.0    
tensorflow-probability             0.4.0     
termcolor                          1.1.0     
terminado                          0.8.1     
testpath                           0.3.1     
toolz                              0.9.0     
tornado                            5.0.2     
tqdm                               4.28.1    
traitlets                          4.3.2     
tweakwcs                           0.5.1     
typing                             3.6.4     
unicodecsv                         0.14.1    
urllib3                            1.22      
VBBinaryLensing                    2.0.5     
wcwidth                            0.1.7     
webbpsf                            0.8.0     
webencodings                       0.5.1     
Werkzeug                           0.14.1    
wfc3tools                          1.3.5     
wfpc2tools                         1.0.4     
wheel                              0.31.1    
widgetsnbextension                 3.2.1     
wrapt                              1.10.11   
xlrd                               1.1.0     
XlsxWriter                         1.0.4     
xlwings                            0.11.8    
xlwt                               1.2.0     
zict                               0.1.3     
zipp                               0.5.1     
`

**Comment by ebachelet** [comment]
Hello

I am currently really busy but I will have a look asap, namely on Friday.

Cheers

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rpoleski** [comment]
@Nijaid , in [MulensModel](https://github.com/rpoleski/MulensModel) we import VBBL in somehow simpler and limited way. The idea is to have a wrapper that changes C++ code to API in pure C ([here](https://github.com/rpoleski/MulensModel/blob/master/source/VBBL/VBBinaryLensingLibrary_wrapper.cpp)), compile this code properly (currently done via [setup.py](https://github.com/rpoleski/MulensModel/blob/master/setup.py), but you can do it using standard gcc or g++), and then import the compiled file in a right way (effectively lines 3, 22, 56, 57, and 60-62 in [binarylens.py](https://github.com/rpoleski/MulensModel/blob/master/source/MulensModel/binarylens.py)). I would say, that in MM we import two most important functions in VBBL and you can easily extend it to other functions. 

This solution was tested some time ago on a couple of different mac os machines. If you try and it fails, please let me know and I'll try to update MulensModel accordingly.

**Comment by ebachelet** [comment]
I recognize that VBB can be tricky to install. Several users succeed to built on Max OSX, but keeping up to date with all builds on all platforms is somewhat challenging due to manpower constraints.  I will be able to help more when I return from a meeting at the end of the week

**Comment by rpoleski** [comment]
Before the previous comment was edited, it started with:

> @rpoleski : This is not a place to advertise other codes but a collaborative platform for the benefit of everyone.

@ebachelet if you don't like the links to other repository on this platform, then I suggest you ask GitHub developers to ban links to GitHub repos in comments.

**Comment by ebachelet** [comment]
Investigations have been made and several upgrades have been made with the PR #12 .
Units tests are passing, installation have been successfully tested on different platforms, including MacOS 10.14 (Mojave). A potential solution would be to update gcc and g++ compiler to version >5.0. 
So I consider this issue as close but feel free to reopen.

**Comment by Nijaid** [comment]
Although I'm working on MacOS 10.12 (Sierra), updating my gcc to 6 seems to have installed everything correctly.
