### ISSUE TITLE
Error in magnification calculation

### ISSUE THREAD

**Issue by rpoleski** [valboz/VBBinaryLensing#16]
I've found that in some cases VBBL artificially results in two high magnification. My case is s = 0.3, q = 0.0019, rho = 0.003, so not an extreme one. Here is specific code:
```c++
double x1, x2, x3, y1, y2, y3, s, q, rho, acc, mag;
VBBinaryLensing VBBL;
x1 = -2.8798499936424813;
x2 = -2.87980198609534;
x3 = -2.879750341503788;
y1 = 0.2603315602357186;
y2 = 0.26034667859291694;
y3 = 0.26036294250727565;
s = 0.3121409537799967;
q = 0.0018654668855723224;
rho = 0.002966662955047919;
acc = 0.001;
mag = VBBL.BinaryMagDark(s, q, x1, y1, rho, 0., acc);
printf("%lf\n", mag);
mag = VBBL.BinaryMagDark(s, q, x2, y2, rho, 0., acc);
printf("%lf\n", mag);
mag = VBBL.BinaryMagDark(s, q, x3, y3, rho, 0., acc);
printf("%lf\n", mag);
```

Based on `(x, y)`, you can see that the second value should be close to the average of the other two. I've run it with VBBL v2.0.1:
```
1.345365
1.368844
1.344216
```
and VBBL v3.4:
```
1.348173
1.372469
1.346418
```
So in both cases, the middle values are off by 0.025. @valboz - can you help with that?

**Comment by valboz** [comment]
Hi Radek, thank you very much for your extensive use and testing. 

Indeed there is an error of 0.03 when working at 0.001 accuracy. I have already tracked the source of the problem: the parabolic correction is not working properly when both end points of the arc lie on flection points. 

Rather than putting an "ad hoc" patch, this is an opportunity for a deeper reformation of the parabolic correction that I already had in mind. However, before releasing a new version, I would like to do some extended testing. Meanwhile, I would suggest you to work at 0.0001 accuracy on these cases.

All the best

 Valerio

**Comment by rpoleski** [comment]
Yes, increasing the requested accuracy is the solution that I had in my mind from the start. I'm looking forward for the full solution. Then I'll update VBBL in MulensModel (which hasn't been done for quite some time).

**Comment by valboz** [comment]
Hi @rpoleski, the new version has new parabolic correction and corresponding error estimator. You shold not find similar problems any more, at least for parameters in a reasonable range. Let me know if you find any issues. Your extensive testing is very precious.

**Comment by rpoleski** [comment]
Thanks a lot @valboz ! I've found more incorrectly calculated magnifications using v2.0 and then checked them using v3.5 - everything worked fine.
