### ISSUE TITLE
images from BinaryMag()

### ISSUE THREAD

**Issue by rpoleski** [valboz/VBBinaryLensing#33]
From `BinaryMag()` I'm getting the `Images`, which is very nice. I've tested it and each image has the same number of points. Is it a rule that I can depend on?

**Comment by valboz** [comment]
Yes you can: for each point in the source boundary I get the corresponding points in the images, which are 3 or 5 depending on the source being outside or inside a caustic. Then, each image boundary is made by the same number of points.

Of course, if part of the source is inside a caustic and part is outside, you will have two merging images, whose number of points will depend on how many points in the source boundary were inside the caustic.

**Comment by rpoleski** [comment]
> ... number of points will depend on ...

It's not clear for me. E.g., if there are 4 images, then the number of points on the boundary is the same for each of these images?

**Comment by valboz** [comment]
4 images are possible only when the source is crossing a caustic. This is what I called "merging images". This "fourth" image is made by some points inside the critical curve and some points outside. These two branches are actually the two additional images formed by the points of the source inside the caustic. Since not all points of the source are inside the caustic, these two merging images are made by a number of points that is less than the total number of points in the source boundary. Ordinary images, instead, have the same number of points, since for each point in the source boundary we have a point on an ordinary image boundary.

**Comment by rpoleski** [comment]
Ok, thanks for the explanations.
